### ISSUE TITLE
Pastebin Link

### ISSUE THREAD

**Issue by Scratchy144** [gregyjames/PasteBin-API#1]
Hey Greg.
Is it possible to get the pastebin link of the pastebin that the api posted?
For example, the API posted an anonymous post, and I want it to write the link to the console. Thanks!

**Comment by gregyjames** [comment]
@Scratchy144 The response from the client.uploadValues function in the uploadAnnon() and uploadAsUser() functions return a byte array that contains the post link if the call was successful. You could try to modify the code to access it but currently there are no way to access the link.
